export const ROUTES = {
  HOME: "/",
  AUTH_X: "/auth/x",
  AUTH_LINKEDIN: "/auth/linkedin",
  AUTH_REDDIT: "/auth/reddit",
  DASHBOARD_X: "/dashboard/x",
  DASHBOARD_X_FEED: "/dashboard/x/feed",
  DASHBOARD_X_SEARCH: "/dashboard/x/search",
  DASHBOARD_LINKEDIN: "/dashboard/linkedin",
  DASHBOARD_REDDIT: "/dashboard/reddit",
  API_AUTH_X_OAUTH: "/api/auth/x/oauth",
  API_AUTH_X_STATUS: "/api/auth/x/status",
  API_AUTH_X_SIGNOUT: "/api/auth/x/signout",
  API_X_FEED: "/api/x/feed",
  API_X_FEED_SAVED: "/api/x/feed/saved",
  API_X_SEARCH_SAVED: "/api/x/search/saved",
  API_X_SEARCH_WITH_REPLIES: "/api/x/search/with-replies",
  API_X_GENERATE_VARIANTS: "/api/x/generate-variants",
  API_X_REPLY: "/api/x/reply",
  API_X_REPLIES_GENERATE: "/api/x/replies/generate",
  API_X_REPLIES_ANALYZE: "/api/x/replies/analyze",
} as const;
